version: 2

models:
  - name: int_customers_cleansed
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: int_orders_cleansed
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('int_customers_cleansed')
              field: customer_id